trigger:
- master

pool:
  name: Default

variables:
  - name: EC2_INSTANCE_IP
    value: $(EC2_IP)
  - name: TOMCAT_MANAGER_USER
    value: $(Tomcat_Username)
  - name: TOMCAT_MANAGER_PASSWORD
    value: $(Tomcat_Password)

jobs:
- job: DeployToTomcat
  steps:
  - task: UseJavaVersion@1
    inputs:
      versionSpec: '21.0.1'
      addToPath: true
      setAsDefault: true

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package'

  - task: TomcatDeployment@1
    inputs:
      TomcatUrl: 'http://$(EC2_INSTANCE_IP):8080'
      Username: $(TOMCAT_MANAGER_USER)
      Password: $(TOMCAT_MANAGER_PASSWORD)
      Warfile: 'target/mvnwebapp.war'
      Context: '/azure-deploy'
      ServerVersion: '7'
